### ISSUE TITLE
Getting same Y-Axis for plot of total tweet per event

### ISSUE THREAD

**Issue by Oliph** [LauraPlanas/MiscarriageTwitterAnalysis#7]
In https://github.com/Oliph/MiscarriageTwitterAnalysis/blob/maria/Clean_miscarriage.ipynb the plot showing the total tweets per day and per event (two subplots side by side) has different y-axis making comparison difficult.

**Comment by mfloresBSC** [comment]
Already fixed on maria's clean notebook
